---
version: 1.2
workflows:
   - name: mirna-seq-pipeline 
     subclass: WDL
     primaryDescriptorPath: /mirna-seq-pipeline.wdl
     authors:
       - name: Otto Jolanki
         orcid: https://orcid.org/0000-0001-8601-4849
